//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap(Locale.init) ?? Locale.current
  fileprivate static let hostingBundle = Bundle(for: R.Class.self)
  
  static func validate() throws {
    try intern.validate()
  }
  
  /// This `R.image` struct is generated, and contains static references to 15 images.
  struct image {
    /// Image `comment`.
    static let comment = Rswift.ImageResource(bundle: R.hostingBundle, name: "comment")
    /// Image `gandhi_profile`.
    static let gandhi_profile = Rswift.ImageResource(bundle: R.hostingBundle, name: "gandhi_profile")
    /// Image `gandhi_status`.
    static let gandhi_status = Rswift.ImageResource(bundle: R.hostingBundle, name: "gandhi_status")
    /// Image `globe_icon`.
    static let globe_icon = Rswift.ImageResource(bundle: R.hostingBundle, name: "globe_icon")
    /// Image `globe_small`.
    static let globe_small = Rswift.ImageResource(bundle: R.hostingBundle, name: "globe_small")
    /// Image `like`.
    static let like = Rswift.ImageResource(bundle: R.hostingBundle, name: "like")
    /// Image `messenger_icon`.
    static let messenger_icon = Rswift.ImageResource(bundle: R.hostingBundle, name: "messenger_icon")
    /// Image `more_icon`.
    static let more_icon = Rswift.ImageResource(bundle: R.hostingBundle, name: "more_icon")
    /// Image `news_feed_icon`.
    static let news_feed_icon = Rswift.ImageResource(bundle: R.hostingBundle, name: "news_feed_icon")
    /// Image `requests_icon`.
    static let requests_icon = Rswift.ImageResource(bundle: R.hostingBundle, name: "requests_icon")
    /// Image `share`.
    static let share = Rswift.ImageResource(bundle: R.hostingBundle, name: "share")
    /// Image `steve_profile`.
    static let steve_profile = Rswift.ImageResource(bundle: R.hostingBundle, name: "steve_profile")
    /// Image `steve_status`.
    static let steve_status = Rswift.ImageResource(bundle: R.hostingBundle, name: "steve_status")
    /// Image `zuckdog`.
    static let zuckdog = Rswift.ImageResource(bundle: R.hostingBundle, name: "zuckdog")
    /// Image `zuckprofile`.
    static let zuckprofile = Rswift.ImageResource(bundle: R.hostingBundle, name: "zuckprofile")
    
    /// `UIImage(named: "comment", bundle: ..., traitCollection: ...)`
    static func comment(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.comment, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "gandhi_profile", bundle: ..., traitCollection: ...)`
    static func gandhi_profile(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.gandhi_profile, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "gandhi_status", bundle: ..., traitCollection: ...)`
    static func gandhi_status(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.gandhi_status, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "globe_icon", bundle: ..., traitCollection: ...)`
    static func globe_icon(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.globe_icon, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "globe_small", bundle: ..., traitCollection: ...)`
    static func globe_small(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.globe_small, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "like", bundle: ..., traitCollection: ...)`
    static func like(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.like, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "messenger_icon", bundle: ..., traitCollection: ...)`
    static func messenger_icon(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.messenger_icon, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "more_icon", bundle: ..., traitCollection: ...)`
    static func more_icon(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.more_icon, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "news_feed_icon", bundle: ..., traitCollection: ...)`
    static func news_feed_icon(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.news_feed_icon, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "requests_icon", bundle: ..., traitCollection: ...)`
    static func requests_icon(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.requests_icon, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "share", bundle: ..., traitCollection: ...)`
    static func share(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.share, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "steve_profile", bundle: ..., traitCollection: ...)`
    static func steve_profile(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.steve_profile, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "steve_status", bundle: ..., traitCollection: ...)`
    static func steve_status(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.steve_status, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "zuckdog", bundle: ..., traitCollection: ...)`
    static func zuckdog(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.zuckdog, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "zuckprofile", bundle: ..., traitCollection: ...)`
    static func zuckprofile(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.zuckprofile, compatibleWith: traitCollection)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.storyboard` struct is generated, and contains static references to 1 storyboards.
  struct storyboard {
    /// Storyboard `LaunchScreen`.
    static let launchScreen = _R.storyboard.launchScreen()
    
    /// `UIStoryboard(name: "LaunchScreen", bundle: ...)`
    static func launchScreen(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.launchScreen)
    }
    
    fileprivate init() {}
  }
  
  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      try _R.validate()
    }
    
    fileprivate init() {}
  }
  
  fileprivate class Class {}
  
  fileprivate init() {}
}

struct _R: Rswift.Validatable {
  static func validate() throws {
    try storyboard.validate()
  }
  
  struct storyboard: Rswift.Validatable {
    static func validate() throws {
      try launchScreen.validate()
    }
    
    struct launchScreen: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UIKit.UIViewController
      
      let bundle = R.hostingBundle
      let name = "LaunchScreen"
      
      static func validate() throws {
        if #available(iOS 11.0, *) {
        }
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  fileprivate init() {}
}
